### ISSUE TITLE
Go get not working

### ISSUE THREAD

**Issue by anidotnet** [povilasv/prommod#11]
When I do `GO111MODULE=on; go get github.com/povilasv/prommod`, I am getting below error:

```
go get github.com/povilasv/prommod: unexpected status (https://gocenter.io/github.com/povilasv/prommod/@v/list): 404 Not Found
```

**Comment by povilasv** [comment]
Hey,

Which go version are you using?

It went fine for me:
```
GO111MODULE=on; go get github.com/povilasv/prommod


```

**Comment by anidotnet** [comment]
go version go1.12.1 linux/amd64. On a second try it seems working, I don't know how it failed first time. Thanks for quick reply.
